config/routes.rb
Chatroom::Application.routes.draw do
  resources :messages

  match 'about/index' => 'about#index'

  root :to => "about#index"

end

app/models/message.rb
class Message
  include Mongoid::Document
  field :user, :type => String
  field :content, :type => String
  field :created, :type => Time
  validates_presence_of :user
  validates_presence_of :content
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @message = Message.new
  end
end

app/controllers/application_controller.rb
#coding:utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  USERNAME, PASSWORD = "root", "123456"

  before_filter :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == USERNAME &&
        password == PASSWORD
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :json
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages.to_xml }
      #p  @messages.as_json.to_s
      #format.json { render :text => @messages.as_json }
      #format.json { render :text => @messages.as_json.to_s.sub(/"_id"=>.+\), /, "") }
      #BSON::ObjectId('4d68093cfd27c00ab9000002'), 
      format.json { 

        temp = @messages.as_json
        #temp.each do |item| 
          #item.delete("_id")
        #end
        #render :text => @messages.as_json.to_s.gsub(/("_id"=>BSON::ObjectId\('.+'\), )?/, "") }
        render :text => temp.to_json}
    end

  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message].merge({:created => Time.now.localtime}))

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
        format.js {render :js => 'updateMessages();$("#message_content").empty();'}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
#coding:utf-8
module ApplicationHelper
  def get_menu_haml(menus)
    menus = ["日记", "相册", "闲聊", "自我介绍"]
    i = 1
    haml = ''
    menus.each do |menu|
      haml += ".grid#{i*2}\r\n"
      haml += "  =link_to #{menu}, #{menu}_path\r\n"
      i += 1
    end
    haml
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/about/index.html.haml
.scroll-pane
  #messages

app/views/layouts/_error.html.haml
- if resource 
  - if resource.errors
    - unless resource.errors.empty?
      %b= "出错啦!"
  %ul
    - resource.errors.full_messages.each do |message|
      %li= "#{message}"

app/views/layouts/_footer.haml
.grid_12
  -#%p &nbsp;
  %hr
  %p!= "Created by Rails 3.0.0, Source Codes : #{link_to 'http://github.com/jinleileiking/lkChatroom', 'http://github.com/jinleileiking/lkChatroom'}, 请使用Chrome浏览器获得最佳效果"

app/views/layouts/_form.html.haml
.gray
  = form_for @message, :remote => true do |f|
    -if @message.errors.any?
      #error_explanation
        %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
        %ul
          - @message.errors.full_messages.each do |msg|
            %li= msg


    -#.field
      -#-#= f.label :content
      -#= f.text_area :content
    -#.field
      -#= f.label "昵称"
      -#= f.text_field :user
    -#.actions
      -#= f.submit '发送'




    .grid_7
      -#= f.label :content
      = f.text_area :content, :class => "send_form"
    .grid_2
      = f.label "昵称", :class => "nickname_lable"
      = f.text_field :user, :class => "nickname_text"
      = f.submit '发送', :class => "clean-gray send_button"

app/views/layouts/_log.html.haml
= link_to '订阅RSS', 'http://www.douban.com/feed/people/jinleileiking/notes'
-#%ul
  -#-if user_signed_in?
    -#%li= "#{current_user.nickname}, 你好!"
    -#%li=link_to '修改账户信息', edit_user_registration_path
    -#-#%li=link_to '修改密码', edit_user_password_path
    -#%li=link_to "注销", destroy_user_session_path
  -#-else
    -#%li=link_to "登录", new_user_session_path  
    -#%li=link_to "注册", new_user_registration_path

app/views/layouts/_menu.html.haml
-#= get_menu_haml @menus
-#.grid_2
  -#%h2=link_to '日记', articles_url
-#-#.grid_2
  -#-#= '相册'
  -#-#=link_to '相册', photos_url
-#.grid_2
  -#%h2=link_to '闲聊', chats_url
-#.grid_2
  -#%h2=link_to '读过的', reads_url
-#.grid_2
  -#%h2=link_to '看过的', watchs_url
-#.grid_2.suffix_2
  -#%h2=link_to '关于自己', about_index_url
-#.clear
-#.grid_2
  %h2 &nbsp;
.grid_7.suffix_5
  %ul#nav
    -#%li=link_to '日记', articles_url
    -#%li=link_to '闲聊', chats_url
    -#%li=link_to '读过的书籍', reads_url
    -#%li=link_to '看过的电影', watchs_url
    %li=link_to '关于自己', about_index_url
.clear

app/views/layouts/_tip.html.haml
- unless flash.empty?
  - if flash.first[0] == :alert
    %b= "出错啦!"
  - flash.each do |name, msg|
    %li= "#{msg}"
-#= p resource
-#- if resource 
  -#- if resource.errors
    -#- unless resource.errors.empty?
      -#%b= "出错啦!"
  -#%ul
    -#- resource.errors.full_messages.each do |message|
      -#%li= "#{message}"

app/views/layouts/application.html.haml
!!!
%html{html_attrs('zh-CN')}
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    %title 自由聊天室
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    -#= formtastic_stylesheet_link_tag
    = csrf_meta_tag
  %body
    .container_12
      .grid_8.suffix_4
        %h1.title 聊天室
        -#= render :partial => 'layouts/log'  
      .clear
      -#= render :partial => 'layouts/menu'
      -#%p &nbsp;
      = render :partial => 'layouts/tip'
      .grid_9
        = yield
      .grid_3
        -#用户列表
        &nbsp;
        = render :partial => 'layouts/users'
      .clear
      = render :partial => 'layouts/form'
      = render :partial => 'layouts/footer'

app/views/messages/_form.html.haml
= form_for @message do |f|
  -if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th User
    %th Content
    %th
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= message.user
      %td= message.content
      %td= link_to 'Show', message
      %td= link_to 'Edit', edit_message_path(message)
      %td= link_to 'Destroy', message, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b User:
  = @message.user
%p
  %b Content:
  = @message.content

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path